### ISSUE TITLE
"Zip bomb detected!" error during parsing of xlsx file

### ISSUE THREAD

**Issue by petromir** [ozlerhakan/poiji#107]
I got the following error when I try to parse one `xlsx` file:

```
Caused by: java.io.IOException: Zip bomb detected! The file would exceed the max. ratio of compressed file size to the size of the expanded data.
This may indicate that the file is used to inflate memory usage and thus could pose a security risk.
You can adjust this limit via ZipSecureFile.setMinInflateRatio() if you need to work with files which exceed this limit.
Uncompressed size: 111838, Raw/compressed size: 1096, ratio: 0.009800
Limits: MIN_INFLATE_RATIO: 0.010000, Entry: xl/styles.xml
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.checkThreshold(ZipArchiveThresholdInputStream.java:131)
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.read(ZipArchiveThresholdInputStream.java:81)
	at org.apache.poi.util.IOUtils.toByteArray(IOUtils.java:152)
	at org.apache.poi.util.IOUtils.toByteArray(IOUtils.java:121)
	at org.apache.poi.openxml4j.util.ZipArchiveFakeEntry.<init>(ZipArchiveFakeEntry.java:47)
	at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource.<init>(ZipInputStreamZipEntrySource.java:53)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:106)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:301)
	at com.poiji.bind.mapping.XSSFUnmarshallerStream.returnFromExcelFile(XSSFUnmarshallerStream.java:42)
```

As the errors suggests we can adjust this limit via `ZipSecureFile.setMinInflateRatio()`, but I don't see how this settings can be passed to Poiji parser.

**Comment by petromir** [comment]
Seems like `ZipSecureFile.setMinInflateRatio()` can be set as a global setting, so it's not relevant to the provided `Poiji` configuration classes
