### ISSUE TITLE
Error when cratea XSSF

### ISSUE THREAD

**Issue by muzamilhaq** [ozlerhakan/poiji#156]
when i create XSSF it keep show error like this

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader;
        at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:138)
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.getTypeLoader(Unknown Source:25)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source:0)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:462)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:265)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:259)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
        at com.sariazhariyah.eassessmentinteraktif.PenilaianFragment$4.onClick(PenilaianFragment.java:188)
```

this my code
```
Workbook wb = new XSSFWorkbook();
                CreationHelper createHelper = wb.getCreationHelper();
                Sheet sheet = wb.createSheet("new sheet");

                Row row = sheet.createRow(0);

                Cell cell = row.createCell(0);
                cell.setCellValue(1);

                row.createCell(1).setCellValue(1.2);
                row.createCell(2).setCellValue(
                        createHelper.createRichTextString("This is a string"));
                row.createCell(3).setCellValue(true);

                try (OutputStream fileOut = new FileOutputStream("workbook.xlsx")) {
                    wb.write(fileOut);
                }catch (IOException e){
                    Log.d("SaveData Exception","Error"+e);
                }
```

**Comment by ozlerhakan** [comment]
Hi @muzamilhaq ,

Could you please look at other related issues? Those could help you out #64 , #110 , #54, #23.
