### ISSUE TITLE
Skip Blank rows between header and data

### ISSUE THREAD

**Issue by abdulrafique** [ozlerhakan/poiji#22]
[DummyData.xlsx](https://github.com/ozlerhakan/poiji/files/1773107/DummyData.xlsx)
While parsing the excel, if there are blank rows between header and actual data, I need the ability to skip those rows, currently it fails with NullPointerException while trying to parse rows:

```
java.lang.NullPointerException: null
	at com.poiji.bind.mapping.PoijiHandler.endRow(PoijiHandler.java:103) ~[poiji-1.8.jar:na]
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.endElement(XSSFSheetXMLHandler.java:389) ~[poi-ooxml-3.14.jar:3.14]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609) ~[na:1.8.0_45]
```

**Comment by ozlerhakan** [comment]
Hi @abdulrafique ,

Thank you for bringing this issue up. I'll take a look at the case soon.

**Comment by ozlerhakan** [comment]
Hi @abdulrafique,

I have fixed the issue so that you can try out the version 1.9 now:

```
<dependency>
  <groupId>com.github.ozlerhakan</groupId>
  <artifactId>poiji</artifactId>
  <version>1.9</version>
</dependency>
```
