### ISSUE TITLE
Problem with POI version java.lang.NoSuchFieldError: CREATE_NULL_AS_BLANK, xlsx files not working

### ISSUE THREAD

**Issue by vashe9** [ozlerhakan/poiji#23]
I'm guetting this error when I try to import a xls file : 

java.lang.NoSuchFieldError: CREATE_NULL_AS_BLANK
	at com.poiji.bind.mapping.HSSFUnmarshaller.isRowEmpty(HSSFUnmarshaller.java:113)
	at com.poiji.bind.mapping.HSSFUnmarshaller.unmarshal(HSSFUnmarshaller.java:52)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:89)
	..

My pom only imports poi only via poiji and when I go the the actual code, it seems to be okay....

 private boolean isRowEmpty(Row row) {
        for (int c = row.getFirstCellNum(); c < row.getLastCellNum(); c++) {
            Cell cell = row.getCell(c, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK);

Xlsx files give another error 

java.lang.NoClassDefFoundError: org/apache/poi/UnsupportedFileFormatException
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:295)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:201)
	at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal(XSSFUnmarshaller.java:43)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:89)
	at be.fgov.sigedis.db2p.support.core.utils.ExcelToPOJOTest.importExcelFile(ExcelToPOJOTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.UnsupportedFileFormatException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more

It seems to be importing poi 3.10.1 (which differs with poi-xml 3.17)...

**Comment by vashe9** [comment]
Actually I had to override the version of poi

<dependency>
			<groupId>com.github.ozlerhakan</groupId>
			<artifactId>poiji</artifactId><version>${poiji.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.poi</groupId>
					<artifactId>poi</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		  <dependency>
		<groupId>org.apache.poi</groupId>
                    <artifactId>poi</artifactId>
                    <version>3.17</version>
            </dependency>

**Comment by vashe9** [comment]
Still getting the same error... The poi version seem to bug. I'm using Spring 3.5 context... 
Caused by: java.lang.NoSuchFieldError: CREATE_NULL_AS_BLANK
        at com.poiji.bind.mapping.HSSFUnmarshaller.isRowEmpty(HSSFUnmarshaller.java:113) [poiji-1.8.jar:]
        at com.poiji.bind.mapping.HSSFUnmarshaller.unmarshal(HSSFUnmarshaller.java:52) [poiji-1.8.jar:]

It's supposed to be using poi 3.17......

**Comment by ozlerhakan** [comment]
Have you tried out 1.9?

**Comment by ozlerhakan** [comment]
You should have the following dependencies after importing poiji, otherwise, try to add the missing dependencies by yourself:

<img width="412" alt="screen shot 2018-03-08 at 10 03 41 am" src="https://user-images.githubusercontent.com/1964927/37137715-194065c2-22b8-11e8-9a0d-4ba0a6db842a.png">

**Comment by ozlerhakan** [comment]
Feel free to comment here, later on, I am closing this thread.

**Comment by vashe9** [comment]
Actually, a jboss provided "Spring io" module was causing the problem, it was always trying to use poi 3.10.1  which doesn't work.
