### ISSUE TITLE
Exception when trying to parse .xlsx file

### ISSUE THREAD

**Issue by vesi-azdio** [ozlerhakan/poiji#241]
It seems XMLHelper.newXMLReader() which is used when parsing .xlsx files is missing.
```
Caused by: java.lang.NoSuchMethodError: 'org.xml.sax.XMLReader org.apache.poi.util.XMLHelper.newXMLReader()'
	at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal0(XSSFUnmarshaller.java:51)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:43)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:35)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:176)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:156)
```

**Comment by ozlerhakan** [comment]
Hi @vesi-azdio ,

Make sure you have the right dependencies on your project when using Poiji. Poiji uses 5.2.1 right now. If you have any comments you can leave it here.
