### ISSUE TITLE
Provider com.bea.xml.stream.EventFactory not found

### ISSUE THREAD

**Issue by HaikuOezu** [ozlerhakan/poiji#31]
Hello
I'm successfully using poiji to read XLS files in my Android app, however after I changed PoijiExcelType.XLS to PoijiExcelType.XLSX in my Poiji.fromExcel() call my app crashes with the following stacktrace

`FATAL EXCEPTION: main
                                                                     Process: com.haistudios.taxman, PID: 7928
                                                                     javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
                                                                         at javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
                                                                         at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
                                                                         at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
                                                                         at javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
                                                                         at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
                                                                         at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
                                                                         at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
                                                                         at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:97)
                                                                         at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
                                                                         at com.poiji.bind.mapping.XSSFUnmarshallerStream.unmarshal(XSSFUnmarshallerStream.java:28)
                                                                         at com.poiji.bind.Poiji.fromExcel(Poiji.java:128)` 

I have tried looking around but I only find very old stuff regarding Eclipse or some Proguard settings that supposedly should help, but I have tried the workarounds and they don't really do anything.
Am I supposed to do something in particular to work with XLSX files on Android?

**Comment by HaikuOezu** [comment]
Actually nevermind, a little bit more reasearch helped me fix the issue! I'm detailing the fix in case somebody else has the same issue.

I included Aalto, an open-source JSR173 provider by adding this to my app's gradle
`compile group: 'com.fasterxml', name: 'aalto-xml', version: '1.0.0'`

Then I told POI to use Aalto with the following code (I put this in my Application's onCreate(), but I assume anywhere else before using Poiji is fine as well
`System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory",
                "com.fasterxml.aalto.stax.InputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory",
                "com.fasterxml.aalto.stax.OutputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory",
                "com.fasterxml.aalto.stax.EventFactoryImpl");`

And now my app is correctly reading XLSX files 👍

**Comment by ozlerhakan** [comment]
wow thank you for the issue and its answer @HaikuOezu
