### ISSUE TITLE
How can we read by "ExcelCellName"

### ISSUE THREAD

**Issue by brobee** [ozlerhakan/poiji#33]
Hi,

First, thank you for your work. This part of the tutorial doesn't show how, it uses index as well. Any example would be helpful! Thanks!

**Comment by ozlerhakan** [comment]
Hi @brobee ,

Is this the example that you didn't understand ?:

```
public class Person {

    @ExcelCell(0)
    protected String name;

    @ExcelCellName("Address")
    protected String address;

    @ExcelCellName("Age")
    protected int age;

    @ExcelCellName("Email")
    protected String email;

}
```

I can elaborate more, if so.

**Comment by brobee** [comment]
I tried to use it without it, but I got the following error:

Object creation:
`static List<TestCaseData> ipTestData = Poiji.fromExcel(new File("src/test/resources/testData/testData.xlsx"), TestCaseData.class);`

TestCaseData:

```
public class TestCaseData {

    @ExcelRow
    private int rowIndex;

    @ExcelCell(0)
    private String abc;
    @ExcelCell(1)
    private String cde;
    @ExcelCell(2)
    private String efg;
}
```

java.lang.ExceptionInInitializerError
Caused by: com.poiji.exception.IllegalCastException: Cannot create a new instance of net.XXX.TestCaseData
	at com.poiji.bind.mapping.PoijiHandler.newInstanceOf(PoijiHandler.java:58)
	at com.poiji.bind.mapping.PoijiHandler.startRow(PoijiHandler.java:119)
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.startElement(XSSFSheetXMLHandler.java:254)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.poiji.bind.mapping.XSSFUnmarshaller.processSheet(XSSFUnmarshaller.java:70)
	at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal0(XSSFUnmarshaller.java:50)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:30)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:64)
	at net.ubs.wma.qa.NEO.Application2.data.TestCaseDataObjects.<clinit>(TestCaseDataObjects.java:17)

**Comment by ozlerhakan** [comment]
I have just created a toy project that contains a poiji dependency. Please take a look at that project and let me know if you don't understand some parts

https://github.com/ozlerhakan/poiji-example

**Comment by brobee** [comment]
Thank you! I really appreciate your answer! However I Struggling with the castexception. It seems to me, all the structure is fine

**Comment by ozlerhakan** [comment]
Do you have the following dependencies when adding poiji in your pom file?

<img width="406" alt="screen shot 2018-06-15 at 11 55 46 pm" src="https://user-images.githubusercontent.com/1964927/41489168-a87ac10a-70f7-11e8-8e10-fa7ecf450821.png">

**Comment by brobee** [comment]
yes, only apache.poi versions are 3.15 not 3.17, but all of them in my external libraries

**Comment by ozlerhakan** [comment]
Could you please explicitly add apache.poi dependency into your pom with 3.17? Perhaps, 3.15 raises this exception.

**Comment by brobee** [comment]
I added manually, no success so far. It is very weird, because if I debug the code, I see the parsed data in ipTestData list. When I want to go on, I got this error. Maybe it is a bug.. What do you think?

**Comment by ozlerhakan** [comment]
Could you share your code with me?

**Comment by brobee** [comment]
Can you please upload the xls file? Maybe this is the problem...

**Comment by ozlerhakan** [comment]
all excel files located here : https://github.com/ozlerhakan/poiji/tree/master/src/test/resources

Which excel file did you use?

**Comment by brobee** [comment]
Wow, it works. Does it matter I use static? I deleted static and your code is fine.

**Comment by ozlerhakan** [comment]
Sounds great @brobee , feel free to open an issue if you have any question. static modifier doesn't work with poiji, yes.
