### ISSUE TITLE
Update README with version of apache poi required to run poiji

### ISSUE THREAD

**Issue by abdulrafique** [ozlerhakan/poiji#54]
I was using apache poi 3.14 and poiji fails to give POJO's in case file is xls. I then have to come and look into your pom to understand Apache poi version supported. It's better to mention it in README file.

Trying to upload a xls file and create POJO:

Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;
	at com.poiji.bind.mapping.HSSFUnmarshaller.isRowEmpty(HSSFUnmarshaller.java:156)
	at com.poiji.bind.mapping.HSSFUnmarshaller.unmarshal(HSSFUnmarshaller.java:61)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:64)

**Comment by ozlerhakan** [comment]
I will mention the version of apache poi. Just note that, If you add poiji in your pom, apache poi dependencies will be downloaded as well since apache poi and its dependencies are the transitive dependencies.
