### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jaimemorales52** [ozlerhakan/poiji#64]
How can I fix this error because I dont know the reason of this error?

I am using the same example, thanks!

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType()Lorg/apache/poi/ss/usermodel/CellType;
	at com.poiji.bind.mapping.HSSFUnmarshaller.isRowEmpty(HSSFUnmarshaller.java:160)
	at com.poiji.bind.mapping.HSSFUnmarshaller.unmarshal(HSSFUnmarshaller.java:56)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:87)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:66)

**Comment by jaimemorales52** [comment]
I have fixed it using the last version of apache poi, 4.0.0.

**Comment by jaimemorales52** [comment]
I have fixed it using the last version of apache poi, 4.0.0.
