### ISSUE TITLE
Want to have empty field "" instead of "null" if my excel sheet contains no value

### ISSUE THREAD

**Issue by nehas510** [ozlerhakan/poiji#74]
I am reading an excel sheet to run my testcases I have a requirement that I need to pass empty parameters in the request, however when I read the empty cell from the excel sheet it gives me "null"

Can you please help?

**Comment by ozlerhakan** [comment]
Could you try using a primitive data type @nehas510 , If It will not work, we can find a way to make this possible.

**Comment by nehas510** [comment]
@ozlerhakan Thanks for the response.  I have all my data as type String.

**Comment by ozlerhakan** [comment]
do you want certain string fields to be an empty string like `""` ? @nehas510

**Comment by nehas510** [comment]
Yes, that's it!

**Comment by ozlerhakan** [comment]
Do you use `preferNullOverDefault()` option @nehas510 ?

**Comment by nehas510** [comment]
NO, I am not using it @ozlerhakan

**Comment by ozlerhakan** [comment]
Okay, you can create your own casting class, so you can set fields empty string:

```
public class MyCasting implements Casting {
    @Override
    public Object castValue(Class<?> fieldType, String value, PoijiOptions options) {
       // if value is null return ""
       // or return value;
    }
}
```
Please check https://github.com/ozlerhakan/poiji#example-6

**Comment by nehas510** [comment]
thanks a lot! I will try and let you know

**Comment by nehas510** [comment]
HI @ozlerhakan , I tried to cast but I am not that much aware of how to use the casting method currently what I am doing is: Created a class: 
```
public class NullCasting implements Casting {
   
	
	@Override
    public Object castValue(Class<?> fieldType, String value, PoijiOptions options) {
       if(value == "null")
    	   value = "";
		
		return value;
    }
}
```

And I am calling it like this : 

```
public class ExcelToPojo {
	
	
	PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings()
            .withCasting(new NullCasting())
            .build();
	
	
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public static Object[] getDatafromExcel(String filePath,Class c) throws IOException{
		Object[] obj;
	File file = new File(filePath);

		obj = (Poiji.fromExcel(new File(file.getCanonicalPath()), c)).toArray();
 
         return obj;

	}
```

I guess I am missing out something, so I am getting this error : 

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set int field model.Activations.rowIndex to java.lang.String
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IllegalArgumentException: Can not set int field model.Activations.rowIndex to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.poiji.bind.mapping.PoijiHandler.setFieldData(PoijiHandler.java:182)
	at com.poiji.bind.mapping.PoijiHandler.setValue(PoijiHandler.java:127)
	at com.poiji.bind.mapping.PoijiHandler.setFieldValue(PoijiHandler.java:69)
	at com.poiji.bind.mapping.PoijiHandler.cell(PoijiHandler.java:225)
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.endElement(XSSFSheetXMLHandler.java:379)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.poiji.bind.mapping.XSSFUnmarshaller.processSheet(XSSFUnmarshaller.java:92)
	at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal0(XSSFUnmarshaller.java:67)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:43)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:36)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:168)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:149)
	at common.ExcelToPojo.getDatafromExcel(ExcelToPojo.java:21)
	at common.TestDataProvider.testCaseProvider_Activation(TestDataProvider.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more

```

It will be a great if you can help me resolve this. Thanks a lot for all the good work!

**Comment by ozlerhakan** [comment]
```java
public class NullCasting implements Casting {

	@Override
        public Object castValue(Class<?> fieldType, String value, PoijiOptions options) {
          if(value == null)
    	     value = "";
		
          return value;
    }
}
```
and you need to create model like https://github.com/ozlerhakan/poiji#example-2 

```java
public class Person {

    @ExcelCellName("Name")  (1)
    protected String name;

    @ExcelCellName("Address")
    protected String address;

    @ExcelCellName("Age")
    protected int age;

    @ExcelCellName("Email")
    protected String email;

}
```
It should work:

```java

PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings()
            .withCasting(new NullCasting())
            .build();

File file = new File(filePath);
List<Person> people = Poiji.fromExcel(file, Person.class, options));
```

**Comment by nehas510** [comment]
This is my method which called the getDatafromExcel method

```
@DataProvider(name = "testcase-provider-activation")

  public static Object[] testCaseProvider_Activation() throws IOException {

         Object[] testData = ExcelToPojo.getDatafromExcel("testData/activation.xlsx",Activations.class);



  return testData;



  }

```


This is my POJO class. Here do I need to specify cell name for casting ?

```
public class Activations {
	
	 @ExcelRow                  
		private int rowIndex;
		 
	 @ExcelCell(0)
	private String testCaseName	;
	 @ExcelCell(1)
	private String guid;
	 @ExcelCell(2)
	private String email;
	 @ExcelCell(3)
	private String language ;
	 @ExcelCell(4)
	private String notify ;
	 @ExcelCell(5)
	private String requestTxn;
	 @ExcelCell(6)
	private String statusCode;
}
 
```

**Comment by ozlerhakan** [comment]
Probably you need some sort of this change:

```java
@DataProvider(name = "testcase-provider-activation")
  public static List<Activations> testCaseProvider_Activation() throws IOException {
         List<Activations> testData = ExcelToPojo.getDatafromExcel("testData/activation.xlsx", Activations.class);
         return testData;
  }
```

and change ExcelToPojo like:

```java
public class ExcelToPojo {

    static PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings()
            .withCasting(new NullCasting())
            .build();

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public static <T> List<T> getDatafromExcel(String filePath, Class<T> c) throws IOException{
        File file = new File(filePath);
        return Poiji.fromExcel(file, c , options);

    }
}
```

**Comment by nehas510** [comment]
HI Sorry for the late response as it was a weekend here.
I will try it today and let you know.

Thanks again for the help
Neha

**Comment by nehas510** [comment]
I exactly used the same way as you mentioned it gives me this error :(
```
[Utils] [ERROR] [Error] java.lang.IllegalArgumentException: Can not set int field model.Activations.rowIndex to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.poiji.bind.mapping.PoijiHandler.setFieldData(PoijiHandler.java:182)
	at com.poiji.bind.mapping.PoijiHandler.setValue(PoijiHandler.java:127)
	at com.poiji.bind.mapping.PoijiHandler.setFieldValue(PoijiHandler.java:69)
	at com.poiji.bind.mapping.PoijiHandler.cell(PoijiHandler.java:225)
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.endElement(XSSFSheetXMLHandler.java:379)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.poiji.bind.mapping.XSSFUnmarshaller.processSheet(XSSFUnmarshaller.java:92)
	at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal0(XSSFUnmarshaller.java:67)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:43)
	at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:36)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:168)
	at com.poiji.bind.Poiji.fromExcel(Poiji.java:149)
	at common.ExcelToPojo.getDatafromExcel(ExcelToPojo.java:25)
	at common.TestDataProvider.testCaseProvider_Activation(TestDataProvider.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

**Comment by ozlerhakan** [comment]
I think, I know the problem. Since you use your own casting implementation that is `NullCasting`.  The casting class return a String value all the time. You need to change the type of `rowIndex` to `String`.

```java
public class Activations {
	
	 @ExcelRow                  
         private String rowIndex;
		 
	 @ExcelCell(0)
	private String testCaseName	;
	 @ExcelCell(1)
	private String guid;
	 @ExcelCell(2)
	private String email;
	 @ExcelCell(3)
	private String language ;
	 @ExcelCell(4)
	private String notify ;
	 @ExcelCell(5)
	private String requestTxn;
	 @ExcelCell(6)
	private String statusCode;
}
```

**Comment by nehas510** [comment]
Hi @ozlerhakan  this resolved the error and it works smooth however Its still taking the value as null instead of empty :(

**Comment by ozlerhakan** [comment]
hmm, one more thing I have in my mind is set all fields with `""` string:

```java
public class Activations {
	
	 @ExcelRow                  
         private String rowIndex;
		 
	 @ExcelCell(0)
	private String testCaseName = ""	;
	 @ExcelCell(1)
	private String guid= "";
	 @ExcelCell(2)
	private String email= "";
	 @ExcelCell(3)
	private String language ;
	 @ExcelCell(4)
	private String notify = "";
	 @ExcelCell(5)
	private String requestTxn;
	 @ExcelCell(6)
	private String statusCode = "";
}
```

If that doesn't work, you need to share the code with us.

**Comment by nehas510** [comment]
@ozlerhakan  It worked!! Yay!! Thanks a lot for all the help!

Keep up the good work! :)

**Comment by ozlerhakan** [comment]
Great that it worked! :)

**Comment by ozlerhakan** [comment]
Hi @hendryang , sorry that I see now your message. `preferNullOverDefault(false)` is the default behavior. It should work with preferNullOverDefault(true) to work with null values. Could you send me a sample excel file so that we can check it out?
