### ISSUE TITLE
NoClassDefFoundError:Failed resolution of :Ljavax/XML/stream/XMLEventFactory

### ISSUE THREAD

**Issue by venkypokala** [ozlerhakan/poiji#79]
NoClassDefFoundError:Failed resolution of :Ljavax/XML/stream/XMLEventFactory in android target API 28. runtime issue

**Comment by ozlerhakan** [comment]
please use the latest version of poiji and check the transitive dependencies of apache poi @venkypokala

**Comment by ozlerhakan** [comment]
feel free to leave a comment if the issue is still alive

**Comment by venkypokala** [comment]
I am using library :    implementation 'com.github.ozlerhakan:poiji:1.20.0'

still am getting this issue 
  java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLEventFactory;
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:140)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:136)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:272)
        at com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:41)
        at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:36)
        at com.poiji.bind.Poiji.fromExcel(Poiji.java:87)
        at com.poiji.bind.Poiji.fromExcel(Poiji.java:66)

Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLEventFactory" on path: DexPathList[[zip file "/data/app/com.mobiapply.pestbox-UAtcVz2YgAZVzJXGW_3_bQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mobiapply.pestbox-UAtcVz2YgAZVzJXGW_3_bQ==/lib/arm64, /data/app/com.mobiapply.pestbox-UAtcVz2YgAZVzJXGW_3_bQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41) 
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:140) 
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:136) 
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:272) 
        at com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:41) 
        at com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:36) 
        at com.poiji.bind.Poiji.fromExcel(Poiji.java:87) 
        at com.poiji.bind.Poiji.fromExcel(Poiji.java:66) 
        at com.mobiapply.ui.common.XLSReaderActivity.onFilesChosen(XLSReaderActivity.java:56) 
        at com.kbeanie.multipicker.core.threads.FileProcessorThread$1.run(FileProcessorThread.java:91) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6792) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by ozlerhakan** [comment]
could you look at these issues first #64, #23
